//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tam.Blog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpList
    {
        public int Id { get; set; }
        public string HTTP_CLIENT_IP { get; set; }
        public string HTTP_X_FORWARDED_FOR { get; set; }
        public string HTTP_X_FORWARDED { get; set; }
        public string HTTP_FORWARDED_FOR { get; set; }
        public string HTTP_FORWARDED { get; set; }
        public string REMOTE_ADDR { get; set; }
        public string PublicIP { get; set; }
        public Nullable<bool> IsMobileTablet { get; set; }
        public string UserAgent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Location1 { get; set; }
        public string Location2 { get; set; }
    }
}
