//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tam.Blog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginHistory
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string IpAdress { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
